---
# handlers file for ansible-role-opendistro

- name: Restart opendistro
  systemd:
    name: "{{ item }}"
    enabled: true
    daemon_reload: true
    state: restarted
  loop: "{{ redhat_services }}"
